# https://github.com/mattn/goreman
etcd: etcd
Golb: golb -config=golb.json
Client: watch 'curl -H "Host:localhost" http://127.0.0.1:8081'
S10001: ./server -addr=:10001
S10002: ./server -addr=:10002
S10003: ./server -addr=:10003
