# https://github.com/mattn/goreman
Golb: golb -config=config.json
Client: watch 'curl -H "Host:localhost" http://127.0.0.1:8081 > /dev/null'
S10001: ./sdserver -addr=:10001
S10002: ./sdserver -addr=:10002
S10003: ./sdserver -addr=:10003
