# https://github.com/mattn/goreman
Golb: golb -config=golb.json
Client: watch 'curl https://localhost:8081 --proxy-cacert server.pem > /dev/null'
S10001: python -m SimpleHTTPServer 10001
S10002: python -m SimpleHTTPServer 10002

